server:
  # cs是否会乱码  test if luanma  2021年5月22日15:11:17
  port: 180888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 81.68.223.33:8848
    sentinel:
      transport:
        dashboard: 81.68.223.33:8080
        port: 8719

  zipkin:
    base-url: 81.68.223.33:9411
    sender:
      type: web
    # 2021年5月25日14:21:22  与sender平级的  这个注解对着老师这项目新加的？ 原来的我pms写错了？
    discovery-client-enabled: false

  sleuth:
    #百分百取样
    sampler:
      probability: 1


feign:
  sentinel:
    enabled: true




#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
