server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 81.68.223.33:8848
#        ip: 81.68.223.33
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
          filters:
            - Auth
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: order-route  #新2021年6月1日17:55:44  day17p3
          uri: lb://order-service
          predicates:
            - Path=/order/**
          fiters:
            - Auth
      x-forwarded:
        host-enabled: true

# day15 p7  网关只有公钥 只有auth自己有私钥
auth:
  jwt:
#    pubKeyPath: D:\\project\\rsa\\rsa.pub
    pubKeyPath: D:\\project\\rsa\\rsa.pub
    cookieName: GMALL-TOKEN